// Maps the Gigsberg feed's plain-English country names to ISO 3166-1 alpha-2
// codes, for react-world-flags (components/Flag.tsx). Built from the distinct
// `country` values actually present in gigsberg_events — not an exhaustive
// world list.
const COUNTRY_CODES: Record<string, string> = {
  Albania: 'AL',
  Andorra: 'AD',
  Argentina: 'AR',
  Armenia: 'AM',
  Australia: 'AU',
  Austria: 'AT',
  Azerbaijan: 'AZ',
  Bahrain: 'BH',
  Belgium: 'BE',
  Bolivia: 'BO',
  'Bosnia And Herzegovina': 'BA',
  Brazil: 'BR',
  Bulgaria: 'BG',
  Canada: 'CA',
  Chile: 'CL',
  Colombia: 'CO',
  'Costa Rica': 'CR',
  Croatia: 'HR',
  Cyprus: 'CY',
  'Czech Republic': 'CZ',
  Denmark: 'DK',
  'Dominican Republic': 'DO',
  Ecuador: 'EC',
  Egypt: 'EG',
  'El Salvador': 'SV',
  Estonia: 'EE',
  'Faroe Islands': 'FO',
  Finland: 'FI',
  France: 'FR',
  Georgia: 'GE',
  Germany: 'DE',
  Gibraltar: 'GI',
  Greece: 'GR',
  Guatemala: 'GT',
  Honduras: 'HN',
  'Hong Kong': 'HK',
  Hungary: 'HU',
  Iceland: 'IS',
  Indonesia: 'ID',
  Ireland: 'IE',
  Italy: 'IT',
  Japan: 'JP',
  Kazakhstan: 'KZ',
  Kosovo: 'XK',
  Latvia: 'LV',
  Lebanon: 'LB',
  Liechtenstein: 'LI',
  Lithuania: 'LT',
  Luxembourg: 'LU',
  Macedonia: 'MK',
  Malaysia: 'MY',
  Malta: 'MT',
  Mexico: 'MX',
  Moldova: 'MD',
  Monaco: 'MC',
  Montenegro: 'ME',
  Morocco: 'MA',
  Netherlands: 'NL',
  'New Zealand': 'NZ',
  Norway: 'NO',
  Panama: 'PA',
  Paraguay: 'PY',
  Peru: 'PE',
  Philippines: 'PH',
  Poland: 'PL',
  Portugal: 'PT',
  'Puerto Rico': 'PR',
  Qatar: 'QA',
  Romania: 'RO',
  'San Marino': 'SM',
  Serbia: 'RS',
  Singapore: 'SG',
  Slovakia: 'SK',
  Slovenia: 'SI',
  'South Africa': 'ZA',
  'South Korea': 'KR',
  Spain: 'ES',
  Sweden: 'SE',
  Switzerland: 'CH',
  Taiwan: 'TW',
  Thailand: 'TH',
  Turkey: 'TR',
  'United Arab Emirates': 'AE',
  'United Kingdom': 'GB',
  'United States': 'US',
};

/** ISO alpha-2 code for a Gigsberg country name, or null when unknown (e.g. "TBA"). */
export function countryCodeFor(country: string | null | undefined): string | null {
  if (!country) return null;
  return COUNTRY_CODES[country] ?? null;
}
