// neop event data — exposed as window.NEOP
(function () {
  const img = (id, w) =>
    `https://images.unsplash.com/photo-${id}?w=${w || 1400}&q=80&auto=format&fit=crop`;

  const CATEGORIES = [
    { id: "music",      label: "Music",        emoji: "♪" },
    { id: "festivals",  label: "Festivals",    emoji: "✦" },
    { id: "sports",     label: "Sports",       emoji: "◆" },
    { id: "arts",       label: "Theater & Arts", emoji: "❖" },
    { id: "comedy",     label: "Comedy",       emoji: "☺" },
    { id: "conferences",label: "Conferences",  emoji: "▣" },
  ];

  const EVENTS = [
    {
      id: "aurora-nights",
      title: "Aurora Nights",
      artist: "ODESZA",
      category: "music",
      genre: "Electronic",
      venue: "Forest Hills Stadium",
      city: "New York",
      country: "USA",
      date: "2026-07-18T20:00:00",
      priceFrom: 89,
      currency: "$",
      hot: true,
      image: img("1459749411175-04bf5292ceea"),
      blurb: "An immersive audiovisual journey under the open sky — ODESZA return with their most ambitious live production yet.",
      lineup: ["ODESZA", "Yotto", "Jai Wolf", "Ben Böhmer"],
    },
    {
      id: "sahara-sound",
      title: "Sahara Sound Festival",
      artist: "60+ artists",
      category: "festivals",
      genre: "Multi-genre",
      venue: "Merzouga Dunes",
      city: "Merzouga",
      country: "Morocco",
      date: "2026-09-04T16:00:00",
      priceFrom: 240,
      currency: "$",
      hot: true,
      image: img("1533174072545-7a4b6ad7a6c3"),
      blurb: "Three nights of sound in the desert. Stages rise from the dunes as the sun sets over the Sahara.",
      lineup: ["Bonobo", "Caribou", "Floating Points", "Peggy Gou", "Four Tet"],
    },
    {
      id: "clasico-final",
      title: "El Clásico — Final",
      artist: "Real Madrid vs Barcelona",
      category: "sports",
      genre: "Football",
      venue: "Santiago Bernabéu",
      city: "Madrid",
      country: "Spain",
      date: "2026-05-23T21:00:00",
      priceFrom: 310,
      currency: "€",
      hot: true,
      image: img("1574629810360-7efbbe195018"),
      blurb: "The fixture that stops the world. Witness football's fiercest rivalry decide the title.",
      lineup: [],
    },
    {
      id: "hamlet-reimagined",
      title: "Hamlet, Reimagined",
      artist: "National Theatre",
      category: "arts",
      genre: "Theater",
      venue: "Olivier Theatre",
      city: "London",
      country: "UK",
      date: "2026-06-11T19:30:00",
      priceFrom: 65,
      currency: "£",
      hot: false,
      image: img("1503095396549-807759245b35"),
      blurb: "A bold, minimalist staging of Shakespeare's masterpiece — performed in the round.",
      lineup: [],
    },
    {
      id: "midnight-laughs",
      title: "Midnight Laughs",
      artist: "Hannah Gadsby",
      category: "comedy",
      genre: "Stand-up",
      venue: "Sydney Opera House",
      city: "Sydney",
      country: "Australia",
      date: "2026-08-02T21:00:00",
      priceFrom: 72,
      currency: "$",
      hot: false,
      image: img("1585699324551-f6c309eedeca"),
      blurb: "An intimate, razor-sharp new hour from one of comedy's most original voices.",
      lineup: [],
    },
    {
      id: "future-stack",
      title: "FutureStack 2026",
      artist: "Tech & Design Summit",
      category: "conferences",
      genre: "Technology",
      venue: "Moscone Center",
      city: "San Francisco",
      country: "USA",
      date: "2026-10-15T09:00:00",
      priceFrom: 499,
      currency: "$",
      hot: false,
      image: img("1540575467063-178a50c2df87"),
      blurb: "Two days on the frontier of AI, design and product. 80 speakers, one stage.",
      lineup: [],
    },
    {
      id: "neon-tokyo",
      title: "Neon Tokyo",
      artist: "Fred again..",
      category: "music",
      genre: "House",
      venue: "Toyosu PIT",
      city: "Tokyo",
      country: "Japan",
      date: "2026-11-08T22:00:00",
      priceFrom: 120,
      currency: "$",
      hot: true,
      image: img("1516450360452-9312f5e86fc7"),
      blurb: "A sweat-soaked night of euphoric house from the producer redefining live electronic music.",
      lineup: ["Fred again..", "Joy Anonymous", "Romy"],
    },
    {
      id: "rio-carnival",
      title: "Rio Carnival Gala",
      artist: "Sambadrome",
      category: "festivals",
      genre: "Carnival",
      venue: "Marquês de Sapucaí",
      city: "Rio de Janeiro",
      country: "Brazil",
      date: "2026-02-14T19:00:00",
      priceFrom: 180,
      currency: "$",
      hot: false,
      image: img("1551972873-b7e8754e8e26"),
      blurb: "The greatest show on Earth. Grandstand seats for the parade of champions.",
      lineup: [],
    },
    {
      id: "courtside-finals",
      title: "NBA Finals — Game 7",
      artist: "Lakers vs Celtics",
      category: "sports",
      genre: "Basketball",
      venue: "Crypto.com Arena",
      city: "Los Angeles",
      country: "USA",
      date: "2026-06-19T20:30:00",
      priceFrom: 540,
      currency: "$",
      hot: true,
      image: img("1546519638-68e109498ffc"),
      blurb: "Winner takes all. The decisive game of the season's greatest rivalry.",
      lineup: [],
    },
    {
      id: "swan-lake",
      title: "Swan Lake",
      artist: "Bolshoi Ballet",
      category: "arts",
      genre: "Ballet",
      venue: "Palais Garnier",
      city: "Paris",
      country: "France",
      date: "2026-12-03T19:00:00",
      priceFrom: 145,
      currency: "€",
      hot: false,
      image: img("1518834107812-67b0b7c58434"),
      blurb: "Tchaikovsky's timeless classic, staged in the gilded splendour of the Palais Garnier.",
      lineup: [],
    },
    {
      id: "berlin-techno",
      title: "Berghain Series",
      artist: "Charlotte de Witte",
      category: "music",
      genre: "Techno",
      venue: "Kraftwerk",
      city: "Berlin",
      country: "Germany",
      date: "2026-07-25T23:00:00",
      priceFrom: 55,
      currency: "€",
      hot: false,
      image: img("1571019613454-1cb2f99b2d8b"),
      blurb: "Industrial techno in a cathedral of concrete. Doors at 11pm, no phones on the floor.",
      lineup: ["Charlotte de Witte", "Amelie Lens", "I Hate Models"],
    },
    {
      id: "coachella-w2",
      title: "Coachella — Weekend 2",
      artist: "Billie Eilish & more",
      category: "festivals",
      genre: "Multi-genre",
      venue: "Empire Polo Club",
      city: "Indio",
      country: "USA",
      date: "2026-04-18T14:00:00",
      priceFrom: 549,
      currency: "$",
      hot: true,
      image: img("1429962714451-bb934ecdc4ec"),
      blurb: "The desert's defining weekend returns with a headline lineup spanning every genre.",
      lineup: ["Billie Eilish", "Tyler, The Creator", "Sabrina Carpenter"],
    },
  ];

  window.NEOP = { CATEGORIES, EVENTS, img };
})();
